### PR TITLE
Add support for $AUTOENV_DISABLED, which skips the chpwd hook

### PR DESCRIPTION
**Pull request by blueyed**
Opinions?

### CODE REVIEW

**Comment by Tarrasch** [comment]
Well, if I wanted to completely disable this plugin, I would just remove it from the source list in my plugin manager. Is this extra logic solving for any new real use cases?

**Comment by blueyed** [comment]
> if I wanted to completely disable this plugin

It's more about disabling it temporarily, in the current shel.

But I'm not sure about it.
You could also disable it (for the current shell) by removing the chpwd hook - which is not that convenient however.

**Comment by Tarrasch** [comment]
> It's more about disabling it temporarily, in the current shel.

Ah I see. Then I think this makes sense, I have no idea how to remove the `chpwd` hook, so this could be helpful I think!

**Comment by blueyed** [comment]
> I have no idea how to remove the chpwd hook

    add-zsh-hook -d chpwd _autoenv_chpwd_handler

Another method might be to just `unfunction chpwd _autoenv_chpwd_handler`.

I am going to merge this PR then.

**Comment by blueyed** [comment]
Added in https://github.com/Tarrasch/zsh-autoenv/commit/e07a47f5662b865608978834bf65ee34d53e2e67, with additional initialization/doc for the setting.

**Comment by Tarrasch** [comment]
Thanks!!

**Pull request closed without merging**
