### PR TITLE
Add zgen instructions

### PR DESCRIPTION
**Pull request by unixorn**

### CODE REVIEW

**Comment by Tarrasch** [comment]
You definitely don't need 3 commits for this. Can you squash?

**Comment by blueyed** [comment]
Committed in 15bc1e3, and slightly reworded.

Thanks @unixorn.

**Comment by Tarrasch** [comment]
Thanks to both of you guys! :)

**Comment by Tarrasch** [comment]
On second thought. I'm not sure I actually like this commit. It's completely useless except spreading the knowledge of the existence of zgen. I mean, if you any other `zgen load` line in your dotfiles, I'm sure you can figure out how to change it for this plugin, particularly since it's exactly the same as for antigen. Hmm...

**Comment by blueyed** [comment]
> except spreading the knowledge of the existence of zgen

Which is good in itself probably.  It isn't too bad to have several plugin systems listed there.

But I agree that we should add more substance to the README / doc..! :)

**Comment by Tarrasch** [comment]
Absolutely. I didn't know of zgen. Though maybe we shouldn't list any and just refer to http://dotfiles.github.io/. Or we just mention antigen-hs since everybody knows and agrees that it's the best? :)

**Comment by unixorn** [comment]
I'm a little biased in favor of zgen, myself :-). I like that it takes the approach of creating an init.zsh that you source, so you only pay the price of finding all the plugins you use once when you change the list instead of every time you start a new shell.

As a dotfiles.github.io maintainer, I certainly don't object to adding a pointer to dotfiles.github.io. :-)

**Comment by Tarrasch** [comment]
Yes. antigen sucks, that's why I created Tarrasch/antigen-hs which does it like zgen only using a type-safe DSL to specify your plugins. :)

**Pull request closed without merging**
