### PR TITLE
_autoenv_hash_pair: use sha1sum (C) instead of shasum (Perl)

### PR DESCRIPTION
**Pull request by blueyed**
This improves performance.

### CODE REVIEW

**Comment by Tarrasch** [comment]
Awesomeness! :)

**Comment by jasisk** [comment]
Worth noting that `sha1sum` is not available on macOS (up to current—Sierra).

**Comment by Tarrasch** [comment]
Thanks. This also raises another question. Was the improved performance improvement noticeable @blueyed?

**Comment by blueyed** [comment]
@Tarrasch 
Yes.. seen it when profiling my shell startup.
We can have a callback though, of course.

@jasisk 
Do you want to create a PR?

**Comment by blueyed** [comment]
@jasisk 
I assume md5sum exists?
Would not be compatible, but maybe this or something else could be used instead?

**Comment by rspeed** [comment]
It does not. That would be `md5` which I see doesn't exist in GNU. Though neither MD5 or SHA-1 is considered cryptographically secure, anyway. If cryptographic security isn't important, the standard option would be `cksum`.

**Pull request merged**
