### PR TITLE
Change default locations of env files

### PR DESCRIPTION
**Pull request by blueyed**
For #31.

While at it, I've also changed the setting name and location for the auth file.

These commits should be squashed then before merging.

### CODE REVIEW

**Comment by blueyed** [comment]
I've thought a bit about migrating existing files, but then thought it was not worth the effort probably (at the current stage / popularity of the project).

I've added the following to get warned myself about `.env` files that might not be sourced now anymore:

    _warn_old_env() {
      if [[ -f $PWD/.env ]]; then
        echo "WARN: found .env file. Should be .autoenv.zsh probably!" >&2
      fi
    }
    add-zsh-hook chpwd _warn_old_env

I've also noticed that moving the existing auth file does not help much, when
the name of the files itself changes (given the defaults).

**Comment by Tarrasch** [comment]
Hmm, maybe add that warning to this repo as well? It could be on by default but you have the option to not register the hook with a config variable. Maybe?

**Comment by blueyed** [comment]
A warning/note in the repo sounds good.
I am not sure, if we should ship the extra chpwd hook though.
You can see a list of used files in your with file anyway.

**Comment by Tarrasch** [comment]
"with file"? But sure, I'm fine with not shipping the chpwd hook.

**Comment by blueyed** [comment]
> "with file"

env file, sorry.

**Comment by Tarrasch** [comment]
So LGTM. :)

**Pull request closed without merging**
