### PR TITLE
cksum authorization

### PR DESCRIPTION
**Pull request by rspeed**
Merge conflict is because I branched from the parent of 448ceefd3a19a91ac124328ae722e5b307c9d62d.

### CODE REVIEW

**Comment by blueyed** [comment]
> I can't get the unit tests working

What does not work?
Have you installed `cram`?
(shouldn't be required - it is fine to fix it with my help/Travis probably)
I will review the PR later/tomorrow.

**Comment by rspeed** [comment]
Yeah,  I installed `cram` through pip, but no matter what I do every test fails with this message:

> AUTOENV_AUTH_FILE is not in /tmp. Aborting. (no-eol)

**Comment by blueyed** [comment]
> I've also played around with automatically upgrading old whitelist entries when they're encountered, though it's not currently in place.

I would prefer that, but it might not be worth the effort: there are likely only about a dozen authenticated files typically at most, and it's OK to get "reminded" of them probably?!
Thinking forward though, we might want to add the version to the auth file, and then grep for the file, and look at the version and hash from there (no additional external program being called).
But still: I'd rather want the hashes being upgraded to the faster one than adding more logic to fallback to old versions - so in this case it would only help with upgrading lazily/on-the-fly.

What about just an extra script that cleans and upgrades the auth file?
It could look at each entry, and for missing files remove them (with confirmation?), and for changed auth hashes update them (basically what gets done now on hash mismatch).

**Comment by rspeed** [comment]
> I would prefer that, but it might not be worth the effort

It's actually ridiculously easy. Just call `_autoenv_authorize` when the v1 hash is found. I just didn't want to clobber the old entries.

I just pushed another change which does exactly that.

**Comment by rspeed** [comment]
I should probably point out that prior to 664df88f4ba82f69f113aa0f1956703744d9afa2, my fork used a slightly different format for the whitelist entry. I was only including the hash portion of the `cksum` output, whereas @blueyed's code includes the file size as well. Better to not toss out entropy!

**Comment by blueyed** [comment]
Yeah, we should merge this soonish.
@Tarrasch ?

**Comment by blueyed** [comment]
@rspeed 
Would be good if you could rebase this on master, squashing everything into a single commit - you can take over ownership of the tests I've fixed/added, but feel free to add some X-Helped-By etc (but not necessary).

I've tried to rebase it, but there are conflicts (like you mentioned).
Might be rather trivial though (I've not looked too closely), so I could also look at it later / tomorrow.

**Comment by rspeed** [comment]
Is "no" an acceptable answer? I'm very much opposed to rewriting SCM history.

**Comment by blueyed** [comment]
But it certainly breaks git-bisect.

**Comment by rspeed** [comment]
I have no opposition to rebasing it over to the master branch, only with squashing commits. Though even then, wouldn't that require that I create a new PR?

**Comment by blueyed** [comment]
No, you can force-push to this branch/PR.

**Comment by rspeed** [comment]
I have no idea how to do that.

**Comment by Tarrasch** [comment]
@rspeed, you could probably google it. :)

Also you don't have permissions to "break" anything. So just try until you make it. ^^

**Comment by rspeed** [comment]
Yeah, that's exactly the problem. I don't have permissions to push to the PR directly.

**Comment by blueyed** [comment]
@rspeed 
Of course.. it is your branch.
Basically `git push --force-with-lease` should work.
(`--force-with-lease` is a bit safer than `-f`).

**Comment by rspeed** [comment]
I can push to my branch all I want, it's still going to be `cksum-authorization`.

**Comment by rspeed** [comment]
There are three options:

1. Explain how I can tell github to look at my fork's `master` branch instead of `cksum-authorization`.
1. Come to terms with the fact that feature branches are a reality.
1. Just do it yourself because you actually have the proper permissions to pull from my fork.

I was happy to help but this is absurd.

**Comment by blueyed** [comment]
> I can push to my branch all I want, it's still going to be cksum-authorization.

Yes, that will update the PR after all.

> 1. Explain how I can tell github to look at my fork's master branch instead of cksum-authorization.

Why should it look at master?  (that is the point of feature branches after all - you can force-push to them).

> I was happy to help but this is absurd.

Sorry to have annoyed you, but it seems like we have some misunderstanding somewhere..

**Comment by rspeed** [comment]
Your concern seemed to be that `git-bisect` wouldn't work, which I can only see as being a problem due to the fact that my merge occurred on a branch with a name other than `master`.

**Comment by blueyed** [comment]
> Your concern seemed to be that git-bisect wouldn't work, which I can only see as being a problem due to the fact that my merge occurred on a branch with a name other than master.

Huh?  You lost me there.

My concern is that `git-bisect` should be good on zsh-autoenv's master.
This means that we should not merge commits which would fail by itself, i.e. running the tests on every commit should be good.
The point here is that if you run git-bisect for some other bug, it should not fail on commits being fixed in a later commit of some merge.

**Comment by Tarrasch** [comment]
@blueyed, hey, won't it be enough to just do a "Squash and merge" as is possible from the GitHub WebUI these days?

**Comment by blueyed** [comment]
@Tarrasch 
Done.

@rspeed 
Thanks!

**Comment by Tarrasch** [comment]
Thanks to both of you for your patches @rspeed and @blueyed. :)

**Pull request merged**
